steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/ofertix",
        "--build-arg",
        "VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}",
        "--build-arg",
        "VITE_SUPABASE_PUBLISHABLE_KEY=${_VITE_SUPABASE_PUBLISHABLE_KEY}",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ofertix"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "run",
        "deploy",
        "ofertix",
        "--image",
        "gcr.io/$PROJECT_ID/ofertix",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/$PROJECT_ID/ofertix"
