name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Se dispara cada vez que subes cambios a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Tu llave de Google Cloud

      - name: Construir y Subir imagen
        run: |
          docker build \
            --build-arg VITE_SUPABASE_URL="${{ secrets.VITE_SUPABASE_URL }}" \
            --build-arg VITE_SUPABASE_ANON_KEY="${{ secrets.VITE_SUPABASE_ANON_KEY }}" \
            -t gcr.io/tu-proyecto/ofertix-frontend .
          docker push gcr.io/tu-proyecto/ofertix-frontend
